### ISSUE TITLE
help how to fix

### ISSUE THREAD

**Issue by silkylol** [DamianeK02/DiscordAccountTokenGenerator#10]
PS C:\Users\wijay> & C:/Users/wijay/AppData/Local/Programs/Python/Python310/python.exe c:/Users/wijay/Downloads/DiscordAccountTokenGenerator-main/main.py
Traceback (most recent call last):
  File "c:\Users\wijay\Downloads\DiscordAccountTokenGenerator-main\main.py", line 86, in <module>
    driver = webdriver.Chrome(chrome_options=option, executable_path=r"C:/Users/wijay/Downloads/DiscordAccountTokenGenerator-main/externals/chromedriver.exe")    
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 95
Current browser version is 97.0.4692.71 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00E43AB3+2505395]
        Ordinal0 [0x00DDAE41+2076225]
        Ordinal0 [0x00CE2498+1057944]
        Ordinal0 [0x00D00841+1181761]
        Ordinal0 [0x00CFC64B+1164875]
        Ordinal0 [0x00CF9EBF+1154751]
        Ordinal0 [0x00D2A02F+1351727]
        Ordinal0 [0x00D29C9A+1350810]
        Ordinal0 [0x00D258BB+1333435]
        Ordinal0 [0x00D023E4+1188836]
        Ordinal0 [0x00D0323F+1192511]
        GetHandleVerifier [0x00FCCB36+1554566]
        GetHandleVerifier [0x01074A0C+2242396]
        GetHandleVerifier [0x00ED0E0B+523099]
        GetHandleVerifier [0x00ECFEB0+519168]
        Ordinal0 [0x00DE02FD+2097917]
        Ordinal0 [0x00DE4388+2114440]
        Ordinal0 [0x00DE44C2+2114754]
        Ordinal0 [0x00DEE041+2154561]
        BaseThreadInitThunk [0x7603FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77D67A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77D67A6E+238]

**Comment by silkylol** [comment]
Traceback (most recent call last):
  File "C:\Users\wijay\Downloads\DiscordAccountTokenGenerator-main\main.py", line 92, in <module>
    get_date()
  File "C:\Users\wijay\Downloads\DiscordAccountTokenGenerator-main\main.py", line 45, in get_date
    driver.find_element_by_xpath(".//div[@class='select-2TCrqx inputDay-18OXiE']").click()
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 520, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\wijay\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":".//div[@class='select-2TCrqx inputDay-18OXiE']"}
  (Session info: chrome=95.0.4638.54)
Stacktrace:
Backtrace:
        Ordinal0 [0x005B3AB3+2505395]
        Ordinal0 [0x0054AE41+2076225]
        Ordinal0 [0x00452498+1057944]
        Ordinal0 [0x0047CB74+1231732]
        Ordinal0 [0x004A6D92+1404306]
        Ordinal0 [0x00495A2A+1333802]
        Ordinal0 [0x004A5168+1397096]
        Ordinal0 [0x004958BB+1333435]
        Ordinal0 [0x004723E4+1188836]
        Ordinal0 [0x0047323F+1192511]
        GetHandleVerifier [0x0073CB36+1554566]
        GetHandleVerifier [0x007E4A0C+2242396]
        GetHandleVerifier [0x00640E0B+523099]
        GetHandleVerifier [0x0063FEB0+519168]
        Ordinal0 [0x005502FD+2097917]
        Ordinal0 [0x00554388+2114440]
        Ordinal0 [0x005544C2+2114754]
        Ordinal0 [0x0055E041+2154561]
        BaseThreadInitThunk [0x7603FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77D67A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77D67A6E+238]

**Comment by DamianeK02** [comment]
Check repo
