### ISSUE TITLE
Backtrace errors 

### ISSUE THREAD

**Issue by kiketi9a** [DamianeK02/DiscordAccountTokenGenerator#18]
Traceback (most recent call last):
  File "C:\Users\Kiketi\Desktop\DiscordAccountTokenGenerator-main\main.py", line 131, in <module>
    start()
  File "C:\Users\Kiketi\Desktop\DiscordAccountTokenGenerator-main\main.py", line 108, in start
    get_date()
  File "C:\Users\Kiketi\Desktop\DiscordAccountTokenGenerator-main\main.py", line 68, in get_date
    driver.find_element(By.XPATH, "/html/body/div[1]/div[2]/div/div[1]/div/div/div/form/div/div/div[4]/div[1]/div[1]/div/div/div/div/div[1]/div[1]").click()
  File "C:\Users\Kiketi\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Kiketi\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kiketi\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/div/div[1]/div/div/div/form/div/div/div[4]/div[1]/div[1]/div/div/div/div/div[1]/div[1]"}
  (Session info: chrome=105.0.5195.102)
Stacktrace:
Backtrace:
        Ordinal0 [0x00C2DF13+2219795]
        Ordinal0 [0x00BC2841+1779777]
        Ordinal0 [0x00AD423D+803389]
        Ordinal0 [0x00B03025+995365]
        Ordinal0 [0x00B031EB+995819]
        Ordinal0 [0x00B30F52+1183570]
        Ordinal0 [0x00B1E844+1108036]
        Ordinal0 [0x00B2F192+1175954]
        Ordinal0 [0x00B1E616+1107478]
        Ordinal0 [0x00AF7F89+950153]
        Ordinal0 [0x00AF8F56+954198]
        GetHandleVerifier [0x00F22CB2+3040210]
        GetHandleVerifier [0x00F12BB4+2974420]
        GetHandleVerifier [0x00CC6A0A+565546]
        GetHandleVerifier [0x00CC5680+560544]
        Ordinal0 [0x00BC9A5C+1808988]
        Ordinal0 [0x00BCE3A8+1827752]
        Ordinal0 [0x00BCE495+1827989]
        Ordinal0 [0x00BD80A4+1867940]
        BaseThreadInitThunk [0x766DFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77007A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77007A6E+238]

**Comment by tympanicblock61** [comment]
ye same

**Comment by VenomRaiden** [comment]
same for me too

**Comment by Poggres543** [comment]
same for me anyone got a solution?

**Comment by Makli26** [comment]
Same

**Comment by DumbDannyLol** [comment]
Working on it. This is a bug I have not seen yet. What is your OS and python version? @kiketi9a

**Comment by DamFerr** [comment]
Ive got this too
```Traceback (most recent call last):
  File "C:\Users\Damián\Downloads\DiscordAccountTokenGenerator-main\main.py", line 131, in <module>
    start()
  File "C:\Users\Damián\Downloads\DiscordAccountTokenGenerator-main\main.py", line 108, in start
    get_date()
  File "C:\Users\Damián\Downloads\DiscordAccountTokenGenerator-main\main.py", line 68, in get_date
    driver.find_element(By.XPATH, "/html/body/div[1]/div[2]/div/div[1]/div/div/div/form/div/div/div[4]/div[1]/div[1]/div/div/div/div/div[1]/div[1]").click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Damián\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Damián\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Damián\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/div/div[1]/div/div/div/form/div/div/div[4]/div[1]/div[1]/div/div/div/div/div[1]/div[1]"}
  (Session info: chrome=107.0.5304.107)
Stacktrace:
Backtrace:
        Ordinal0 [0x00B3ACD3+2075859]
        Ordinal0 [0x00ACEE61+1633889]
        Ordinal0 [0x009CB7BD+571325]
        Ordinal0 [0x009FAC2F+764975]
        Ordinal0 [0x009FAE1B+765467]
        Ordinal0 [0x00A2D0F2+970994]
        Ordinal0 [0x00A17364+881508]
        Ordinal0 [0x00A2B56A+963946]
        Ordinal0 [0x00A17136+880950]
        Ordinal0 [0x009EFEFD+720637]
        Ordinal0 [0x009F0F3F+724799]
        GetHandleVerifier [0x00DEEED2+2769538]
        GetHandleVerifier [0x00DE0D95+2711877]
        GetHandleVerifier [0x00BCA03A+521194]
        GetHandleVerifier [0x00BC8DA0+516432]
        Ordinal0 [0x00AD682C+1665068]
        Ordinal0 [0x00ADB128+1683752]
        Ordinal0 [0x00ADB215+1683989]
        Ordinal0 [0x00AE6484+1729668]
        BaseThreadInitThunk [0x75E37BA9+25]
        RtlInitializeExceptionChain [0x76EDBB9B+107]
        RtlClearBits [0x76EDBB1F+191]```

**Comment by superjohn04** [comment]
I am using Windows 10 with Visual Studio Code. And it is using Python version 3.10.8

**Comment by DamianeK02** [comment]
sorry but this project is no longer supported
